## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './home-credit-default-risk/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./home-credit-default-risk/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [4]:
row_num = format(app_train.shape[0],',') #為讓數字容易閱讀，加上千分位，row_num的type為字符串
clm_num = app_train.shape[1] #clm_num的type為int
print('row數為：%s'%(row_num))
print('column數為：%d'%(clm_num))

row數為：307,511
column數為：122

#### 列出所有欄位

In [5]:
#col_name初始化
col_name = [] 

#==製作col_name的列表，以供後面製作Column Name的字典使用==
for i in range(len(app_train.columns)): 
    col_name.append(app_train.columns[i]) 
    #其實這時候只要下一步print(col_name)就能顯示所有欄位了，
    #不過為了讓顯示的結果更美觀，所以進行以下的處理。

#==製作Column Name的字典，以供後面製作Column Name的表格使用==
dict1 = {
    'Column Name':col_name
}

#==變更顯示的rows的最大值==
pd.set_option("max_rows",len(app_train.columns)) #語法是pd.set_option("max_rows",int)
                                                                      #在這邊的int代表希望顯示的最大rows數。
                                                                      #int必須是正整數。

#==製作Column Name的表格==
df = pd.DataFrame(dict1)
df

                      Column Name
0                      SK_ID_CURR
1                          TARGET
2              NAME_CONTRACT_TYPE
3                     CODE_GENDER
4                    FLAG_OWN_CAR
5                 FLAG_OWN_REALTY
6                    CNT_CHILDREN
7                AMT_INCOME_TOTAL
8                      AMT_CREDIT
9                     AMT_ANNUITY
10                AMT_GOODS_PRICE
11                NAME_TYPE_SUITE
12               NAME_INCOME_TYPE
13            NAME_EDUCATION_TYPE
14             NAME_FAMILY_STATUS
15              NAME_HOUSING_TYPE
16     REGION_POPULATION_RELATIVE
17                     DAYS_BIRTH
18                  DAYS_EMPLOYED
19              DAYS_REGISTRATION
20                DAYS_ID_PUBLISH
21                    OWN_CAR_AGE
22                     FLAG_MOBIL
23                 FLAG_EMP_PHONE
24                FLAG_WORK_PHONE
25               FLAG_CONT_MOBILE
26                     FLAG_PHONE
27                     FLAG_EMAIL
28                OCCUPATION_TYPE
29                CNT_FAM_MEMBERS
30           REGION_RATING_CLIENT
31    REGION_RATING_CLIENT_W_CITY
32     WEEKDAY_APPR_PROCESS_START
33        HOUR_APPR_PROCESS_START
34     REG_REGION_NOT_LIVE_REGION
35     REG_REGION_NOT_WORK_REGION
36    LIVE_REGION_NOT_WORK_REGION
37         REG_CITY_NOT_LIVE_CITY
38         REG_CITY_NOT_WORK_CITY
39        LIVE_CITY_NOT_WORK_CITY
40              ORGANIZATION_TYPE
41                   EXT_SOURCE_1
42                   EXT_SOURCE_2
43                   EXT_SOURCE_3
44                 APARTMENTS_AVG
45               BASEMENTAREA_AVG
46    YEARS_BEGINEXPLUATATION_AVG
47                YEARS_BUILD_AVG
48                 COMMONAREA_AVG
49                  ELEVATORS_AVG
50                  ENTRANCES_AVG
51                  FLOORSMAX_AVG
52                  FLOORSMIN_AVG
53                   LANDAREA_AVG
54           LIVINGAPARTMENTS_AVG
55                 LIVINGAREA_AVG
56        NONLIVINGAPARTMENTS_AVG
57              NONLIVINGAREA_AVG
58                APARTMENTS_MODE
59              BASEMENTAREA_MODE
60   YEARS_BEGINEXPLUATATION_MODE
61               YEARS_BUILD_MODE
62                COMMONAREA_MODE
63                 ELEVATORS_MODE
64                 ENTRANCES_MODE
65                 FLOORSMAX_MODE
66                 FLOORSMIN_MODE
67                  LANDAREA_MODE
68          LIVINGAPARTMENTS_MODE
69                LIVINGAREA_MODE
70       NONLIVINGAPARTMENTS_MODE
71             NONLIVINGAREA_MODE
72                APARTMENTS_MEDI
73              BASEMENTAREA_MEDI
74   YEARS_BEGINEXPLUATATION_MEDI
75               YEARS_BUILD_MEDI
76                COMMONAREA_MEDI
77                 ELEVATORS_MEDI
78                 ENTRANCES_MEDI
79                 FLOORSMAX_MEDI
80                 FLOORSMIN_MEDI
81                  LANDAREA_MEDI
82          LIVINGAPARTMENTS_MEDI
83                LIVINGAREA_MEDI
84       NONLIVINGAPARTMENTS_MEDI
85             NONLIVINGAREA_MEDI
86             FONDKAPREMONT_MODE
87                 HOUSETYPE_MODE
88                 TOTALAREA_MODE
89             WALLSMATERIAL_MODE
90            EMERGENCYSTATE_MODE
91       OBS_30_CNT_SOCIAL_CIRCLE
92       DEF_30_CNT_SOCIAL_CIRCLE
93       OBS_60_CNT_SOCIAL_CIRCLE
94       DEF_60_CNT_SOCIAL_CIRCLE
95         DAYS_LAST_PHONE_CHANGE
96                FLAG_DOCUMENT_2
97                FLAG_DOCUMENT_3
98                FLAG_DOCUMENT_4
99                FLAG_DOCUMENT_5
100               FLAG_DOCUMENT_6
101               FLAG_DOCUMENT_7
102               FLAG_DOCUMENT_8
103               FLAG_DOCUMENT_9
104              FLAG_DOCUMENT_10
105              FLAG_DOCUMENT_11
106              FLAG_DOCUMENT_12
107              FLAG_DOCUMENT_13
108              FLAG_DOCUMENT_14
109              FLAG_DOCUMENT_15
110              FLAG_DOCUMENT_16
111              FLAG_DOCUMENT_17
112              FLAG_DOCUMENT_18
113              FLAG_DOCUMENT_19
114              FLAG_DOCUMENT_20
115              FLAG_DOCUMENT_21
116    AMT_REQ_CREDIT_BUREAU_HOUR
117     AMT_REQ_CREDIT_BUREAU_DAY
118    AMT_REQ_CREDIT_BUREAU_WEEK
119     AMT_REQ_CREDIT_BUREAU_MON
120     AMT_REQ_CREDIT_BUREAU_QRT
121    AMT_REQ_CREDIT_BUREAU_YEAR

#### 截取部分資料

In [6]:
#==顯示rows:9~11；columns:'DAYS_EMPLOYED'~'DAYS_ID_PUBLISH' 的資料==
app_train.loc[9:10,'DAYS_EMPLOYED':'DAYS_ID_PUBLISH']

    DAYS_EMPLOYED  DAYS_REGISTRATION  DAYS_ID_PUBLISH
9           -2019           -14437.0            -3992
10           -679            -4427.0             -738

In [7]:
#==顯示rows:9~11；columns:18~20 的資料==
app_train.iloc[9:11,18:21]

    DAYS_EMPLOYED  DAYS_REGISTRATION  DAYS_ID_PUBLISH
9           -2019           -14437.0            -3992
10           -679            -4427.0             -738

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子